// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reader.proto

package proto.reader;

public final class Reader {
  private Reader() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ReadResultSetRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.reader.ReadResultSetRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string resultSetId = 1;</code>
     */
    boolean hasResultSetId();
    /**
     * <code>optional string resultSetId = 1;</code>
     */
    java.lang.String getResultSetId();
    /**
     * <code>optional string resultSetId = 1;</code>
     */
    com.google.protobuf.ByteString
        getResultSetIdBytes();

    /**
     * <code>optional int32 chunkSize = 2;</code>
     */
    boolean hasChunkSize();
    /**
     * <code>optional int32 chunkSize = 2;</code>
     */
    int getChunkSize();
  }
  /**
   * Protobuf type {@code proto.reader.ReadResultSetRequest}
   */
  public static final class ReadResultSetRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.reader.ReadResultSetRequest)
      ReadResultSetRequestOrBuilder {
    // Use ReadResultSetRequest.newBuilder() to construct.
    private ReadResultSetRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReadResultSetRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReadResultSetRequest defaultInstance;
    public static ReadResultSetRequest getDefaultInstance() {
      return defaultInstance;
    }

    public ReadResultSetRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReadResultSetRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              resultSetId_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              chunkSize_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.reader.Reader.internal_static_proto_reader_ReadResultSetRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.reader.Reader.internal_static_proto_reader_ReadResultSetRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.reader.Reader.ReadResultSetRequest.class, proto.reader.Reader.ReadResultSetRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<ReadResultSetRequest> PARSER =
        new com.google.protobuf.AbstractParser<ReadResultSetRequest>() {
      public ReadResultSetRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReadResultSetRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReadResultSetRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RESULTSETID_FIELD_NUMBER = 1;
    private java.lang.Object resultSetId_;
    /**
     * <code>optional string resultSetId = 1;</code>
     */
    public boolean hasResultSetId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string resultSetId = 1;</code>
     */
    public java.lang.String getResultSetId() {
      java.lang.Object ref = resultSetId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          resultSetId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string resultSetId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResultSetIdBytes() {
      java.lang.Object ref = resultSetId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resultSetId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHUNKSIZE_FIELD_NUMBER = 2;
    private int chunkSize_;
    /**
     * <code>optional int32 chunkSize = 2;</code>
     */
    public boolean hasChunkSize() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 chunkSize = 2;</code>
     */
    public int getChunkSize() {
      return chunkSize_;
    }

    private void initFields() {
      resultSetId_ = "";
      chunkSize_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getResultSetIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, chunkSize_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getResultSetIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, chunkSize_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static proto.reader.Reader.ReadResultSetRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.reader.Reader.ReadResultSetRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.reader.Reader.ReadResultSetRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.reader.Reader.ReadResultSetRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.reader.Reader.ReadResultSetRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.reader.Reader.ReadResultSetRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static proto.reader.Reader.ReadResultSetRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static proto.reader.Reader.ReadResultSetRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static proto.reader.Reader.ReadResultSetRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.reader.Reader.ReadResultSetRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.reader.Reader.ReadResultSetRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.reader.ReadResultSetRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.reader.ReadResultSetRequest)
        proto.reader.Reader.ReadResultSetRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.reader.Reader.internal_static_proto_reader_ReadResultSetRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.reader.Reader.internal_static_proto_reader_ReadResultSetRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.reader.Reader.ReadResultSetRequest.class, proto.reader.Reader.ReadResultSetRequest.Builder.class);
      }

      // Construct using proto.reader.Reader.ReadResultSetRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        resultSetId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        chunkSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.reader.Reader.internal_static_proto_reader_ReadResultSetRequest_descriptor;
      }

      public proto.reader.Reader.ReadResultSetRequest getDefaultInstanceForType() {
        return proto.reader.Reader.ReadResultSetRequest.getDefaultInstance();
      }

      public proto.reader.Reader.ReadResultSetRequest build() {
        proto.reader.Reader.ReadResultSetRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.reader.Reader.ReadResultSetRequest buildPartial() {
        proto.reader.Reader.ReadResultSetRequest result = new proto.reader.Reader.ReadResultSetRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.resultSetId_ = resultSetId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.chunkSize_ = chunkSize_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.reader.Reader.ReadResultSetRequest) {
          return mergeFrom((proto.reader.Reader.ReadResultSetRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.reader.Reader.ReadResultSetRequest other) {
        if (other == proto.reader.Reader.ReadResultSetRequest.getDefaultInstance()) return this;
        if (other.hasResultSetId()) {
          bitField0_ |= 0x00000001;
          resultSetId_ = other.resultSetId_;
          onChanged();
        }
        if (other.hasChunkSize()) {
          setChunkSize(other.getChunkSize());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.reader.Reader.ReadResultSetRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.reader.Reader.ReadResultSetRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object resultSetId_ = "";
      /**
       * <code>optional string resultSetId = 1;</code>
       */
      public boolean hasResultSetId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string resultSetId = 1;</code>
       */
      public java.lang.String getResultSetId() {
        java.lang.Object ref = resultSetId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            resultSetId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string resultSetId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResultSetIdBytes() {
        java.lang.Object ref = resultSetId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resultSetId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string resultSetId = 1;</code>
       */
      public Builder setResultSetId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        resultSetId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string resultSetId = 1;</code>
       */
      public Builder clearResultSetId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        resultSetId_ = getDefaultInstance().getResultSetId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string resultSetId = 1;</code>
       */
      public Builder setResultSetIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        resultSetId_ = value;
        onChanged();
        return this;
      }

      private int chunkSize_ ;
      /**
       * <code>optional int32 chunkSize = 2;</code>
       */
      public boolean hasChunkSize() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 chunkSize = 2;</code>
       */
      public int getChunkSize() {
        return chunkSize_;
      }
      /**
       * <code>optional int32 chunkSize = 2;</code>
       */
      public Builder setChunkSize(int value) {
        bitField0_ |= 0x00000002;
        chunkSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 chunkSize = 2;</code>
       */
      public Builder clearChunkSize() {
        bitField0_ = (bitField0_ & ~0x00000002);
        chunkSize_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.reader.ReadResultSetRequest)
    }

    static {
      defaultInstance = new ReadResultSetRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.reader.ReadResultSetRequest)
  }

  public interface ReadResultSetResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.reader.ReadResultSetResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .proto.JdbcDataRow rows = 1;</code>
     */
    java.util.List<proto.Common.JdbcDataRow> 
        getRowsList();
    /**
     * <code>repeated .proto.JdbcDataRow rows = 1;</code>
     */
    proto.Common.JdbcDataRow getRows(int index);
    /**
     * <code>repeated .proto.JdbcDataRow rows = 1;</code>
     */
    int getRowsCount();
    /**
     * <code>repeated .proto.JdbcDataRow rows = 1;</code>
     */
    java.util.List<? extends proto.Common.JdbcDataRowOrBuilder> 
        getRowsOrBuilderList();
    /**
     * <code>repeated .proto.JdbcDataRow rows = 1;</code>
     */
    proto.Common.JdbcDataRowOrBuilder getRowsOrBuilder(
        int index);

    /**
     * <code>optional bool isCompleted = 2;</code>
     */
    boolean hasIsCompleted();
    /**
     * <code>optional bool isCompleted = 2;</code>
     */
    boolean getIsCompleted();
  }
  /**
   * Protobuf type {@code proto.reader.ReadResultSetResponse}
   */
  public static final class ReadResultSetResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.reader.ReadResultSetResponse)
      ReadResultSetResponseOrBuilder {
    // Use ReadResultSetResponse.newBuilder() to construct.
    private ReadResultSetResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReadResultSetResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReadResultSetResponse defaultInstance;
    public static ReadResultSetResponse getDefaultInstance() {
      return defaultInstance;
    }

    public ReadResultSetResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReadResultSetResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                rows_ = new java.util.ArrayList<proto.Common.JdbcDataRow>();
                mutable_bitField0_ |= 0x00000001;
              }
              rows_.add(input.readMessage(proto.Common.JdbcDataRow.PARSER, extensionRegistry));
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              isCompleted_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          rows_ = java.util.Collections.unmodifiableList(rows_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.reader.Reader.internal_static_proto_reader_ReadResultSetResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.reader.Reader.internal_static_proto_reader_ReadResultSetResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.reader.Reader.ReadResultSetResponse.class, proto.reader.Reader.ReadResultSetResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<ReadResultSetResponse> PARSER =
        new com.google.protobuf.AbstractParser<ReadResultSetResponse>() {
      public ReadResultSetResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReadResultSetResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReadResultSetResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ROWS_FIELD_NUMBER = 1;
    private java.util.List<proto.Common.JdbcDataRow> rows_;
    /**
     * <code>repeated .proto.JdbcDataRow rows = 1;</code>
     */
    public java.util.List<proto.Common.JdbcDataRow> getRowsList() {
      return rows_;
    }
    /**
     * <code>repeated .proto.JdbcDataRow rows = 1;</code>
     */
    public java.util.List<? extends proto.Common.JdbcDataRowOrBuilder> 
        getRowsOrBuilderList() {
      return rows_;
    }
    /**
     * <code>repeated .proto.JdbcDataRow rows = 1;</code>
     */
    public int getRowsCount() {
      return rows_.size();
    }
    /**
     * <code>repeated .proto.JdbcDataRow rows = 1;</code>
     */
    public proto.Common.JdbcDataRow getRows(int index) {
      return rows_.get(index);
    }
    /**
     * <code>repeated .proto.JdbcDataRow rows = 1;</code>
     */
    public proto.Common.JdbcDataRowOrBuilder getRowsOrBuilder(
        int index) {
      return rows_.get(index);
    }

    public static final int ISCOMPLETED_FIELD_NUMBER = 2;
    private boolean isCompleted_;
    /**
     * <code>optional bool isCompleted = 2;</code>
     */
    public boolean hasIsCompleted() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool isCompleted = 2;</code>
     */
    public boolean getIsCompleted() {
      return isCompleted_;
    }

    private void initFields() {
      rows_ = java.util.Collections.emptyList();
      isCompleted_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < rows_.size(); i++) {
        output.writeMessage(1, rows_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(2, isCompleted_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < rows_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, rows_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isCompleted_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static proto.reader.Reader.ReadResultSetResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.reader.Reader.ReadResultSetResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.reader.Reader.ReadResultSetResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.reader.Reader.ReadResultSetResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.reader.Reader.ReadResultSetResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.reader.Reader.ReadResultSetResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static proto.reader.Reader.ReadResultSetResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static proto.reader.Reader.ReadResultSetResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static proto.reader.Reader.ReadResultSetResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.reader.Reader.ReadResultSetResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.reader.Reader.ReadResultSetResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.reader.ReadResultSetResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.reader.ReadResultSetResponse)
        proto.reader.Reader.ReadResultSetResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.reader.Reader.internal_static_proto_reader_ReadResultSetResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.reader.Reader.internal_static_proto_reader_ReadResultSetResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.reader.Reader.ReadResultSetResponse.class, proto.reader.Reader.ReadResultSetResponse.Builder.class);
      }

      // Construct using proto.reader.Reader.ReadResultSetResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRowsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (rowsBuilder_ == null) {
          rows_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          rowsBuilder_.clear();
        }
        isCompleted_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.reader.Reader.internal_static_proto_reader_ReadResultSetResponse_descriptor;
      }

      public proto.reader.Reader.ReadResultSetResponse getDefaultInstanceForType() {
        return proto.reader.Reader.ReadResultSetResponse.getDefaultInstance();
      }

      public proto.reader.Reader.ReadResultSetResponse build() {
        proto.reader.Reader.ReadResultSetResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.reader.Reader.ReadResultSetResponse buildPartial() {
        proto.reader.Reader.ReadResultSetResponse result = new proto.reader.Reader.ReadResultSetResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (rowsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            rows_ = java.util.Collections.unmodifiableList(rows_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.rows_ = rows_;
        } else {
          result.rows_ = rowsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.isCompleted_ = isCompleted_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.reader.Reader.ReadResultSetResponse) {
          return mergeFrom((proto.reader.Reader.ReadResultSetResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.reader.Reader.ReadResultSetResponse other) {
        if (other == proto.reader.Reader.ReadResultSetResponse.getDefaultInstance()) return this;
        if (rowsBuilder_ == null) {
          if (!other.rows_.isEmpty()) {
            if (rows_.isEmpty()) {
              rows_ = other.rows_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRowsIsMutable();
              rows_.addAll(other.rows_);
            }
            onChanged();
          }
        } else {
          if (!other.rows_.isEmpty()) {
            if (rowsBuilder_.isEmpty()) {
              rowsBuilder_.dispose();
              rowsBuilder_ = null;
              rows_ = other.rows_;
              bitField0_ = (bitField0_ & ~0x00000001);
              rowsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRowsFieldBuilder() : null;
            } else {
              rowsBuilder_.addAllMessages(other.rows_);
            }
          }
        }
        if (other.hasIsCompleted()) {
          setIsCompleted(other.getIsCompleted());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.reader.Reader.ReadResultSetResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.reader.Reader.ReadResultSetResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<proto.Common.JdbcDataRow> rows_ =
        java.util.Collections.emptyList();
      private void ensureRowsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          rows_ = new java.util.ArrayList<proto.Common.JdbcDataRow>(rows_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          proto.Common.JdbcDataRow, proto.Common.JdbcDataRow.Builder, proto.Common.JdbcDataRowOrBuilder> rowsBuilder_;

      /**
       * <code>repeated .proto.JdbcDataRow rows = 1;</code>
       */
      public java.util.List<proto.Common.JdbcDataRow> getRowsList() {
        if (rowsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rows_);
        } else {
          return rowsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.JdbcDataRow rows = 1;</code>
       */
      public int getRowsCount() {
        if (rowsBuilder_ == null) {
          return rows_.size();
        } else {
          return rowsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.JdbcDataRow rows = 1;</code>
       */
      public proto.Common.JdbcDataRow getRows(int index) {
        if (rowsBuilder_ == null) {
          return rows_.get(index);
        } else {
          return rowsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.JdbcDataRow rows = 1;</code>
       */
      public Builder setRows(
          int index, proto.Common.JdbcDataRow value) {
        if (rowsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowsIsMutable();
          rows_.set(index, value);
          onChanged();
        } else {
          rowsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.JdbcDataRow rows = 1;</code>
       */
      public Builder setRows(
          int index, proto.Common.JdbcDataRow.Builder builderForValue) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.set(index, builderForValue.build());
          onChanged();
        } else {
          rowsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.JdbcDataRow rows = 1;</code>
       */
      public Builder addRows(proto.Common.JdbcDataRow value) {
        if (rowsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowsIsMutable();
          rows_.add(value);
          onChanged();
        } else {
          rowsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.JdbcDataRow rows = 1;</code>
       */
      public Builder addRows(
          int index, proto.Common.JdbcDataRow value) {
        if (rowsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowsIsMutable();
          rows_.add(index, value);
          onChanged();
        } else {
          rowsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.JdbcDataRow rows = 1;</code>
       */
      public Builder addRows(
          proto.Common.JdbcDataRow.Builder builderForValue) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.add(builderForValue.build());
          onChanged();
        } else {
          rowsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.JdbcDataRow rows = 1;</code>
       */
      public Builder addRows(
          int index, proto.Common.JdbcDataRow.Builder builderForValue) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.add(index, builderForValue.build());
          onChanged();
        } else {
          rowsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.JdbcDataRow rows = 1;</code>
       */
      public Builder addAllRows(
          java.lang.Iterable<? extends proto.Common.JdbcDataRow> values) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, rows_);
          onChanged();
        } else {
          rowsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.JdbcDataRow rows = 1;</code>
       */
      public Builder clearRows() {
        if (rowsBuilder_ == null) {
          rows_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          rowsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.JdbcDataRow rows = 1;</code>
       */
      public Builder removeRows(int index) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.remove(index);
          onChanged();
        } else {
          rowsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.JdbcDataRow rows = 1;</code>
       */
      public proto.Common.JdbcDataRow.Builder getRowsBuilder(
          int index) {
        return getRowsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.JdbcDataRow rows = 1;</code>
       */
      public proto.Common.JdbcDataRowOrBuilder getRowsOrBuilder(
          int index) {
        if (rowsBuilder_ == null) {
          return rows_.get(index);  } else {
          return rowsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.JdbcDataRow rows = 1;</code>
       */
      public java.util.List<? extends proto.Common.JdbcDataRowOrBuilder> 
           getRowsOrBuilderList() {
        if (rowsBuilder_ != null) {
          return rowsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rows_);
        }
      }
      /**
       * <code>repeated .proto.JdbcDataRow rows = 1;</code>
       */
      public proto.Common.JdbcDataRow.Builder addRowsBuilder() {
        return getRowsFieldBuilder().addBuilder(
            proto.Common.JdbcDataRow.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.JdbcDataRow rows = 1;</code>
       */
      public proto.Common.JdbcDataRow.Builder addRowsBuilder(
          int index) {
        return getRowsFieldBuilder().addBuilder(
            index, proto.Common.JdbcDataRow.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.JdbcDataRow rows = 1;</code>
       */
      public java.util.List<proto.Common.JdbcDataRow.Builder> 
           getRowsBuilderList() {
        return getRowsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          proto.Common.JdbcDataRow, proto.Common.JdbcDataRow.Builder, proto.Common.JdbcDataRowOrBuilder> 
          getRowsFieldBuilder() {
        if (rowsBuilder_ == null) {
          rowsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              proto.Common.JdbcDataRow, proto.Common.JdbcDataRow.Builder, proto.Common.JdbcDataRowOrBuilder>(
                  rows_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          rows_ = null;
        }
        return rowsBuilder_;
      }

      private boolean isCompleted_ ;
      /**
       * <code>optional bool isCompleted = 2;</code>
       */
      public boolean hasIsCompleted() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool isCompleted = 2;</code>
       */
      public boolean getIsCompleted() {
        return isCompleted_;
      }
      /**
       * <code>optional bool isCompleted = 2;</code>
       */
      public Builder setIsCompleted(boolean value) {
        bitField0_ |= 0x00000002;
        isCompleted_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isCompleted = 2;</code>
       */
      public Builder clearIsCompleted() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isCompleted_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.reader.ReadResultSetResponse)
    }

    static {
      defaultInstance = new ReadResultSetResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.reader.ReadResultSetResponse)
  }

  public interface CloseResultSetRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.reader.CloseResultSetRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string resultSetId = 1;</code>
     */
    boolean hasResultSetId();
    /**
     * <code>optional string resultSetId = 1;</code>
     */
    java.lang.String getResultSetId();
    /**
     * <code>optional string resultSetId = 1;</code>
     */
    com.google.protobuf.ByteString
        getResultSetIdBytes();
  }
  /**
   * Protobuf type {@code proto.reader.CloseResultSetRequest}
   */
  public static final class CloseResultSetRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.reader.CloseResultSetRequest)
      CloseResultSetRequestOrBuilder {
    // Use CloseResultSetRequest.newBuilder() to construct.
    private CloseResultSetRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CloseResultSetRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CloseResultSetRequest defaultInstance;
    public static CloseResultSetRequest getDefaultInstance() {
      return defaultInstance;
    }

    public CloseResultSetRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CloseResultSetRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              resultSetId_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.reader.Reader.internal_static_proto_reader_CloseResultSetRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.reader.Reader.internal_static_proto_reader_CloseResultSetRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.reader.Reader.CloseResultSetRequest.class, proto.reader.Reader.CloseResultSetRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<CloseResultSetRequest> PARSER =
        new com.google.protobuf.AbstractParser<CloseResultSetRequest>() {
      public CloseResultSetRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CloseResultSetRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CloseResultSetRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RESULTSETID_FIELD_NUMBER = 1;
    private java.lang.Object resultSetId_;
    /**
     * <code>optional string resultSetId = 1;</code>
     */
    public boolean hasResultSetId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string resultSetId = 1;</code>
     */
    public java.lang.String getResultSetId() {
      java.lang.Object ref = resultSetId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          resultSetId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string resultSetId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResultSetIdBytes() {
      java.lang.Object ref = resultSetId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resultSetId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      resultSetId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getResultSetIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getResultSetIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static proto.reader.Reader.CloseResultSetRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.reader.Reader.CloseResultSetRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.reader.Reader.CloseResultSetRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.reader.Reader.CloseResultSetRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.reader.Reader.CloseResultSetRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.reader.Reader.CloseResultSetRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static proto.reader.Reader.CloseResultSetRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static proto.reader.Reader.CloseResultSetRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static proto.reader.Reader.CloseResultSetRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.reader.Reader.CloseResultSetRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.reader.Reader.CloseResultSetRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.reader.CloseResultSetRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.reader.CloseResultSetRequest)
        proto.reader.Reader.CloseResultSetRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.reader.Reader.internal_static_proto_reader_CloseResultSetRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.reader.Reader.internal_static_proto_reader_CloseResultSetRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.reader.Reader.CloseResultSetRequest.class, proto.reader.Reader.CloseResultSetRequest.Builder.class);
      }

      // Construct using proto.reader.Reader.CloseResultSetRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        resultSetId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.reader.Reader.internal_static_proto_reader_CloseResultSetRequest_descriptor;
      }

      public proto.reader.Reader.CloseResultSetRequest getDefaultInstanceForType() {
        return proto.reader.Reader.CloseResultSetRequest.getDefaultInstance();
      }

      public proto.reader.Reader.CloseResultSetRequest build() {
        proto.reader.Reader.CloseResultSetRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.reader.Reader.CloseResultSetRequest buildPartial() {
        proto.reader.Reader.CloseResultSetRequest result = new proto.reader.Reader.CloseResultSetRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.resultSetId_ = resultSetId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.reader.Reader.CloseResultSetRequest) {
          return mergeFrom((proto.reader.Reader.CloseResultSetRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.reader.Reader.CloseResultSetRequest other) {
        if (other == proto.reader.Reader.CloseResultSetRequest.getDefaultInstance()) return this;
        if (other.hasResultSetId()) {
          bitField0_ |= 0x00000001;
          resultSetId_ = other.resultSetId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.reader.Reader.CloseResultSetRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.reader.Reader.CloseResultSetRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object resultSetId_ = "";
      /**
       * <code>optional string resultSetId = 1;</code>
       */
      public boolean hasResultSetId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string resultSetId = 1;</code>
       */
      public java.lang.String getResultSetId() {
        java.lang.Object ref = resultSetId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            resultSetId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string resultSetId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResultSetIdBytes() {
        java.lang.Object ref = resultSetId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resultSetId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string resultSetId = 1;</code>
       */
      public Builder setResultSetId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        resultSetId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string resultSetId = 1;</code>
       */
      public Builder clearResultSetId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        resultSetId_ = getDefaultInstance().getResultSetId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string resultSetId = 1;</code>
       */
      public Builder setResultSetIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        resultSetId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.reader.CloseResultSetRequest)
    }

    static {
      defaultInstance = new CloseResultSetRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.reader.CloseResultSetRequest)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_reader_ReadResultSetRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_reader_ReadResultSetRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_reader_ReadResultSetResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_reader_ReadResultSetResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_reader_CloseResultSetRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_reader_CloseResultSetRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014reader.proto\022\014proto.reader\032\014common.pro" +
      "to\">\n\024ReadResultSetRequest\022\023\n\013resultSetI" +
      "d\030\001 \001(\t\022\021\n\tchunkSize\030\002 \001(\005\"N\n\025ReadResult" +
      "SetResponse\022 \n\004rows\030\001 \003(\0132\022.proto.JdbcDa" +
      "taRow\022\023\n\013isCompleted\030\002 \001(\010\",\n\025CloseResul" +
      "tSetRequest\022\023\n\013resultSetId\030\001 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.Common.getDescriptor(),
        }, assigner);
    internal_static_proto_reader_ReadResultSetRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_reader_ReadResultSetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_reader_ReadResultSetRequest_descriptor,
        new java.lang.String[] { "ResultSetId", "ChunkSize", });
    internal_static_proto_reader_ReadResultSetResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_reader_ReadResultSetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_reader_ReadResultSetResponse_descriptor,
        new java.lang.String[] { "Rows", "IsCompleted", });
    internal_static_proto_reader_CloseResultSetRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_reader_CloseResultSetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_reader_CloseResultSetRequest_descriptor,
        new java.lang.String[] { "ResultSetId", });
    proto.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
